import { type DataStreamWriter, tool } from 'ai';
import { z } from 'zod';
interface FormatMemoProps {
  dataStream: DataStreamWriter;
}

export const dueDiligenceQuestions = ({ dataStream }: FormatMemoProps) =>
  tool({
    description:
      'Use this tool when the user asks to write an initial due-diligence request to get the desired output format',
    parameters: z.object({}),
    execute: async () => {
      return `
## Initial due-diligence request

### A. Business Model  
1. …  
2. …  
3. …  

### B. Market Opportunity  
1. …  
2. …  
3. …  

### C. Financial Health  
1. …  
2. …  
3. …  

### D. Leadership Team  
1. …  
2. …  
3. …  

### E. Risks & Challenges  
1. …  
2. …  
3. …  
`;
    },
  });
